### ISSUE TITLE
Activity plot fails

### ISSUE THREAD

**Issue by tomituominen** [michenriksen/birdwatcher#4]
[-] NameError: undefined local variable or method `screen_name' for #<Birdwatcher::Modules::Statuses::ActivityPlot:0xb3b4ad68>
/var/lib/gems/2.1.0/gems/birdwatcher-0.4.0/lib/birdwatcher/modules/users/activity_plot.rb:41:in `run'
/var/lib/gems/2.1.0/gems/birdwatcher-0.4.0/lib/birdwatcher/module.rb:159:in `execute'
/var/lib/gems/2.1.0/gems/birdwatcher-0.4.0/lib/birdwatcher/commands/run.rb:15:in `run'
/var/lib/gems/2.1.0/gems/birdwatcher-0.4.0/lib/birdwatcher/command.rb:47:in `execute'
/var/lib/gems/2.1.0/gems/birdwatcher-0.4.0/lib/birdwatcher/console.rb:43:in `block in handle_input'
/var/lib/gems/2.1.0/gems/birdwatcher-0.4.0/lib/birdwatcher/console.rb:41:in `each'
/var/lib/gems/2.1.0/gems/birdwatcher-0.4.0/lib/birdwatcher/console.rb:41:in `handle_input'
/var/lib/gems/2.1.0/gems/birdwatcher-0.4.0/lib/birdwatcher/commands/resource.rb:40:in `block in run'
/var/lib/gems/2.1.0/gems/birdwatcher-0.4.0/lib/birdwatcher/commands/resource.rb:37:in `each_line'
/var/lib/gems/2.1.0/gems/birdwatcher-0.4.0/lib/birdwatcher/commands/resource.rb:37:in `run'
/var/lib/gems/2.1.0/gems/birdwatcher-0.4.0/lib/birdwatcher/command.rb:47:in `execute'
/var/lib/gems/2.1.0/gems/birdwatcher-0.4.0/lib/birdwatcher/console.rb:43:in `block in handle_input'
/var/lib/gems/2.1.0/gems/birdwatcher-0.4.0/lib/birdwatcher/console.rb:41:in `each'
/var/lib/gems/2.1.0/gems/birdwatcher-0.4.0/lib/birdwatcher/console.rb:41:in `handle_input'
/var/lib/gems/2.1.0/gems/birdwatcher-0.4.0/lib/birdwatcher/console.rb:31:in `start!'
/var/lib/gems/2.1.0/gems/birdwatcher-0.4.0/exe/birdwatcher:12:in `<top (required)>'
/usr/local/bin/birdwatcher:22:in `load'
/usr/local/bin/birdwatcher:22:in `<main>'

**Comment by tomituominen** [comment]
Okay, this is caused by the case sensitivity of the screen name. I did not check whether the APIs require screen names to be case sensitive but it might make sense to lowercase all screen names?

**Comment by michenriksen** [comment]
Hi Tomi, thanks for reporting. Yes, it would make sense to match screen names case-insensitive. I will modify the modules to do so!
